# Generated by Django 5.2 on 2025-04-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dresses', '0006_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company', models.CharField(max_length=100)),
                ('pickup_information', models.TextField()),
                ('Expected_delivery_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Shipment Created', 'Shipment Created'), ('Picked Up from Sender', 'Picked Up from Sender'), ('In Transit', 'In Transit'), ('out for Delivery', 'out for Delivery'), ('Delivered', 'Delivered'), ('Delivery Failed', 'Delivery Failed'), ('On Hold', 'On Hold'), ('Returned to Sender', 'Returned to Sender'), ('Shipment Canceled', 'Shipment Canceled')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.rental')),
            ],
        ),
    ]
