# Generated by Django 5.2 on 2025-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Shipment Created', 'Shipment Created'), ('Picked Up from Sender', 'Picked Up from Sender'), ('In Transit', 'In Transit'), ('out for Delivery', 'out for Delivery'), ('Delivered', 'Delivered'), ('Delivery Failed', 'Delivery Failed'), ('On Hold', 'On Hold'), ('Returned to Sender', 'Returned to Sender'), ('Shipment Canceled', 'Shipment Canceled')], max_length=100),
        ),
    ]
