# Generated by Django 5.2 on 2025-04-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
        ('shipping', '0003_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='dresses.rental'),
        ),
    ]
