# Generated by Django 5.2 on 2025-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_payment_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='request',
            new_name='rental',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='request',
            new_name='rental',
        ),
    ]
