# Generated by Django 5.2 on 2025-05-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
        ('shipping', '0005_rename_request_payment_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='dresses.rental'),
        ),
    ]
