# Generated by Django 5.1.6 on 2025-05-01 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_alter_shipment_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='pickup_information',
            new_name='Pick_up_address',
        ),
        migrations.AddField(
            model_name='shipment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_Pick_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='owner_phone',
            field=models.IntegerField(default=504323217),
            preserve_default=False,
        ),
    ]
