# Generated by Django 5.2 on 2025-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_alter_shipment_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
