# Generated by Django 5.2 on 2025-05-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_rename_pickup_information_shipment_pick_up_address_and_more'),
        ('shipping', '0007_shipment_tracking_url'),
    ]

    operations = [
    ]
