# Generated by Django 5.2 on 2025-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_remove_payment_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=100),
        ),
    ]
