# Generated by Django 5.2 on 2025-05-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_merge_20250503_1521'),
        ('shipping', '0009_alter_payment_status'),
    ]

    operations = [
    ]
