# Generated by Django 5.1.6 on 2025-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_merge_20250505_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='moyasar_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
