# Generated by Django 5.1.6 on 2025-04-28 08:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Dress Owner')], default='customer', max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='SA')),
                ('city', models.CharField(blank=True, choices=[('riyadh', 'Riyadh'), ('jeddah', 'Jeddah'), ('dammam', 'Dammam'), ('abha', 'Abha')], max_length=20, null=True)),
                ('profile_image', models.ImageField(default='images/avatars/avatar.webp', upload_to='images/avatars/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
