# Generated by Django 5.2 on 2025-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('party', 'Party'), ('evening', 'Evening')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='dress_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='dress_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
