# Generated by Django 5.2 on 2025-04-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0002_dress_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dresses.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dress_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
