# Generated by Django 5.2 on 2025-04-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
