# Generated by Django 5.2 on 2025-04-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0004_dress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='image',
            field=models.ImageField(upload_to='images/dresses/dress_img/'),
        ),
    ]
