# Generated by Django 5.2 on 2025-04-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('comments', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rentalrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalDuration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refID', models.IntegerField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Refunded', 'Refunded')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rentalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company', models.CharField(max_length=100)),
                ('pickup_information', models.TextField()),
                ('Expected_delivery_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Shipment Created', 'Shipment Created'), ('Picked Up from Sender', 'Picked Up from Sender'), ('In Transit', 'In Transit'), ('out for Delivery', 'out for Delivery'), ('Delivered', 'Delivered'), ('Delivery Failed', 'Delivery Failed'), ('On Hold', 'Delivery Failed'), ('Returned to Sender', 'Returned to Sender'), ('Shipment Canceled', 'Shipment Canceled')], max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rentalrequest')),
            ],
        ),
    ]
