# Generated by Django 5.2 on 2025-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(choices=[('riyadh', 'Riyadh'), ('jeddah', 'Jeddah'), ('dammam', 'Dammam'), ('abha', 'Abha')], max_length=100),
        ),
    ]
