# Generated by Django 5.2 on 2025-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='shipping_company',
            field=models.CharField(choices=[('Aramex', 'Aramex'), ('SMSA Express', 'SMSA Express')], default='Aramex', max_length=100),
        ),
    ]
