# Generated by Django 5.2 on 2025-04-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_adress_shipping_company'),
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='rental',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dresses.rental'),
            preserve_default=False,
        ),
    ]
