# Generated by Django 5.2 on 2025-04-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='City',
            new_name='city',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
