# Generated by Django 5.1.6 on 2025-05-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_adress_rental'),
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='rental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dresses.rental'),
        ),
    ]
