# Generated by Django 5.2 on 2025-05-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_adress_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
